In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Importing the dataset and selecting the columns

In [22]:
dataset = pd.read_csv('train.csv')
dataset.drop(dataset.columns[[0,5,6,7,9,10,11,12,13,14,16,17,18,19]], axis = 1, inplace = True)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

array([['M', 'Y', 'N', ..., 0, 0.631220343, 5],
       ['M', 'Y', 'Y', ..., 0, 0.392746019, 3],
       ['M', 'Y', 'Y', ..., 0, 0.222536676, 2],
       ...,
       ['F', 'Y', 'Y', ..., 1, 0.826586671, 1],
       ['M', 'Y', 'Y', ..., 0, 0.103523331, 5],
       ['M', 'Y', 'Y', ..., 1, 0.435078756, 5]], dtype=object)

#Encoding the categorical variables

In [23]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
le = LabelEncoder()
#gender
X[:, 0] = le.fit_transform(X[:, 2])
#s11
X[:, 1] = le.fit_transform(X[:, 2])
#s12
X[:, 2] = le.fit_transform(X[:, 2])
#s58
X[:, 5] = le.fit_transform(X[:, 2])

In [24]:
X=pd.DataFrame(X)
X[9].replace(to_replace = 'l', value ='1',inplace=True)
X[9].replace(to_replace = 'o', value ='0',inplace=True)

In [25]:
#extracting numerical values from s54
X[10].replace(to_replace = 'b2', value ='0',inplace=True)
X[10].replace(to_replace = '2b', value ='0',inplace=True)
X[10].replace(to_replace = 'bb', value ='0',inplace=True)
X[10].replace(to_replace = 'aa', value ='1',inplace=True)
X[10].replace(to_replace = 'a2', value ='1',inplace=True)
X[10].replace(to_replace = '2a', value ='1',inplace=True)
X[10].replace(to_replace = 'ab', value ='3',inplace=True)
X[10].replace(to_replace = 'ba', value ='3',inplace=True)
X[10].replace(to_replace = '22', value ='2',inplace=True)

X[11].replace(to_replace = 'kK', value ='0',inplace=True)
X[11].replace(to_replace = 'kk', value ='0',inplace=True)
X[11].replace(to_replace = '2K', value ='0',inplace=True)
X[11].replace(to_replace = 'k2', value ='0',inplace=True)
X[11].replace(to_replace = 'KK', value ='0',inplace=True)
X[11].replace(to_replace = 'Kk', value ='0',inplace=True)
X[11].replace(to_replace = '2k', value ='0',inplace=True)
X[11].replace(to_replace = 'K2', value ='0',inplace=True)
X[11].replace(to_replace = '22', value ='1',inplace=True)


In [39]:
'''from sklearn.impute import SimpleImputer 
imputer=SimpleImputer(missing_values=np.NAN,strategy='mean',fill_value=None,verbose=0,copy=True)
imputer=imputer.fit(X[:,:]) 
X[:,:]=imputer.transform(X[:,:])'''

"from sklearn.impute import SimpleImputer \nimputer=SimpleImputer(missing_values=np.NAN,strategy='mean',fill_value=None,verbose=0,copy=True)\nimputer=imputer.fit(X[:,:]) \nX[:,:]=imputer.transform(X[:,:])"

#Splitting the dataset

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [27]:
print(y_train)

[0 0 0 ... 0 0 0]


#Feature Scaling

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training the RandomForest model on the Training set

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

#Predicting test-set results

In [30]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


#Making the confusion matrix

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[6897  191]
 [1026  383]]


0.8567729786983641