In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Importing the dataset and selecting the columns

In [2]:
dataset = pd.read_csv('datathon_train.csv')
dataset.drop(dataset.columns[[0,5,6,7,9,10,11,12,13,14,16,17,18,19]], axis = 1, inplace = True)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
X

array([['M', 'Y', 'N', ..., 0, 0.631220343, 5],
       ['M', 'Y', 'Y', ..., 0, 0.392746019, 3],
       ['M', 'Y', 'Y', ..., 0, 0.222536676, 2],
       ...,
       ['F', 'Y', 'Y', ..., 1, 0.826586671, 1],
       ['M', 'Y', 'Y', ..., 0, 0.103523331, 5],
       ['M', 'Y', 'Y', ..., 1, 0.435078756, 5]], dtype=object)

#Encoding the categorical variables

In [13]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
le = LabelEncoder()
#gender
X[:, 0] = le.fit_transform(X[:, 2])
#s11
X[:, 1] = le.fit_transform(X[:, 2])
#s12
X[:, 2] = le.fit_transform(X[:, 2])
#s58
X[:, 5] = le.fit_transform(X[:, 2])

In [14]:
'''from sklearn.impute import SimpleImputer 
imputer=SimpleImputer(missing_values=np.NAN,strategy='mean',fill_value=None,verbose=0,copy=True)
imputer=imputer.fit(X[:,:]) 
X[:,:]=imputer.transform(X[:,:])'''

"from sklearn.impute import SimpleImputer \nimputer=SimpleImputer(missing_values=np.NAN,strategy='mean',fill_value=None,verbose=0,copy=True)\nimputer=imputer.fit(X[:,:]) \nX[:,:]=imputer.transform(X[:,:])"

#Splitting the dataset

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [18]:
print(y_train)

[0 0 0 ... 0 0 0]


#Feature Scaling

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training the SVM model on the Training set

In [20]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

#Predicting test-set results

In [21]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


#Making the confusion matrix

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4678   24]
 [ 888   75]]


0.8390114739629303